### ISSUE TITLE
Datapack and Plugin Clash (Module disabled)

### ISSUE THREAD

**Issue by PaladinFallen** [Coll1234567/MineTweaks#1]
So having the data pack and this plugin will cause the plugin not to load, even with module disabled.

[18:15:16] [Server thread/ERROR]: Error occurred while enabling MineTweaks v1.0.0 (Is it up to date?)
java.lang.IllegalStateException: Duplicate recipe ignored with ID minetweaks:cobblestone_stairs_extra
	at net.minecraft.world.item.crafting.RecipeManager.addRecipe(RecipeManager.java:89) ~[app:?]
	at org.bukkit.craftbukkit.v1_17_R1.inventory.CraftShapedRecipe.addToCraftingManager(CraftShapedRecipe.java:58) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.addRecipe(CraftServer.java:1392) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.Bukkit.addRecipe(Bukkit.java:853) ~[patched_1.17.1.jar:git-Paper-325]
	at me.jishuna.minetweaks.modules.RecipeModule.addRecipe(RecipeModule.java:149) ~[MineTweaks-1.0.0.jar:?]
	at me.jishuna.minetweaks.modules.RecipeModule.reload(RecipeModule.java:135) ~[MineTweaks-1.0.0.jar:?]
	at me.jishuna.minetweaks.api.module.TweakModule.<init>(TweakModule.java:35) ~[MineTweaks-1.0.0.jar:?]
	at me.jishuna.minetweaks.modules.RecipeModule.<init>(RecipeModule.java:26) ~[MineTweaks-1.0.0.jar:?]
	at me.jishuna.minetweaks.MineTweaks.registerBaseModules(MineTweaks.java:45) ~[MineTweaks-1.0.0.jar:?]
	at me.jishuna.minetweaks.MineTweaks.onEnable(MineTweaks.java:29) ~[MineTweaks-1.0.0.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:502) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[patched_1.17.1.jar:git-Paper-325]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:458) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:317) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-325]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-325]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]

**Comment by PaladinFallen** [comment]
Everything works perfect now, keep up the good work!!!
